name: build-nrf52
on:
  push:
    paths:
      - 'firmware/**'
      - 'firmware-bluetooth/**'
  workflow_call:
defaults:
  run:
    shell: bash --noprofile --norc -x -e -o pipefail {0}
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        board: ["adafruit_feather_nrf52840", "seeed_xiao_nrf52840"]
    steps:
      - uses: actions/checkout@v6